name: Continuous Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.165.0"
          extended: true

      - name: Show Hugo version
        run: hugo version

      - name: Build website
        run: hugo --minify

      - name: Deploy via rsync
        uses: Burnett01/rsync-deployments@v9
        with:
          switches: -avz --delete
          path: public/
          remote_path: /home/paziwedu/www/arbeitsrecht-winter.ch/
          remote_host: sl239.web.hostpoint.ch
          remote_user: paziwedu
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}
